# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e99ae7807dd5e72dc0f489bfbb318bb90ad4356eea4a3f784f0083c00506e911997713f3f4ea0a7fb7a81e0e5838ebf2683ee7ef6c57a8c914d6db773b04086

test:
  secret_key_base: ca6cd755b7b67c37fa54166ce7157fd0f4f68a4b87e479ef6b5018741bc61b2867b57c6ce84189b6b6a996e4617c16e16d810ce8317177ffe46ab42dc93ce118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
